#ifndef __PlayerLivePage__
#define __PlayerLivePage__

/**
@file
Subclass of LivePage, which is generated by wxFormBuilder.
*/

#include "LivePage.h"
#include "RenderTimer.h"
#include<mutex>
#include<vector>
#include<Windows.h>
#include "wx/dcbuffer.h"
#include "wx/filefn.h"
#include "wx/dir.h"
#include<map>
#include"Controller.h"

extern "C"
{
#include "SDL2/SDL.h"
#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
#include<libavutil/frame.h>
#include <libswscale/swscale.h>
#include <libswresample/swresample.h>
#include "libavdevice/avdevice.h"
#include "libavcodec/avcodec.h"
#include "libavformat/avformat.h"
#include "libswscale/swscale.h"
#include "libavdevice/avdevice.h"
#include "libavutil/imgutils.h"
}

using std::mutex;
using std::vector;
using std::map;

//// end generated include

/** Implementing LivePage */
class PlayerLivePage : public LivePage
{
	private:
		RenderTimer *timer = NULL;
		vector<AVFrame *> frameVec{};
		mutex mtx{};
		Controller controller{};
		map<int, wxString> fileCache{};

	protected:
		// Handlers for LivePage events.
		void paintEvent(wxPaintEvent& event);
		void processSlideOnSlider(wxCommandEvent& event);
		void videoSelect(wxListEvent& event);
		void chooseFolder(wxCommandEvent& event);
		void renderPic(wxDC *dc);
	public:
		/** Constructor */
		PlayerLivePage( wxWindow* parent );
		
	//// end generated class members

};

#endif // __PlayerLivePage__
