#ifndef __PlayerLivePage__
#define __PlayerLivePage__

/**
@file
Subclass of LivePage, which is generated by wxFormBuilder.
*/

#include "LivePage.h"

//// end generated include

/** Implementing LivePage */
class PlayerLivePage : public LivePage
{
	protected:
		// Handlers for LivePage events.
		void videoSelect( wxListEvent& event );
		void chooseFolder( wxCommandEvent& event );
	public:
		/** Constructor */
		PlayerLivePage( wxWindow* parent );
	//// end generated class members

};

#endif // __PlayerLivePage__
